services:
  client:
    build:
      context: client
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app/
      - /app/node_modules
    env_file: .env
    networks:
      - exchange_nw

  api:
    build:
      context: api
      target: dev
    ports:
      - 4000:4000
    env_file: .env
    volumes:
      - ./api/:/app/
      - /app/node_modules
    depends_on:
      - order_queue
    networks:
      - exchange_nw

  matching-engine:
    build:
      context: matching-engine
      target: dev
    volumes:
      - ./matching-engine/:/app/
      - /app/node_modules
    depends_on:
      - order_queue
    networks:
      - exchange_nw
    env_file: .env

  order_queue:
    image: redis
    networks:
      - exchange_nw

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    env_file: .env
    ports:
      - 5432:5432
    # volumes:
    #   - timescale-data:/var/lib/postgresql/data
    networks:
      - exchange_nw

  store:
    build:
      context: store
      target: dev
    networks:
      - exchange_nw
    volumes:
      - ./store/:/app/
      - /app/node_modules
    depends_on:
      - order_queue
      - timescaledb
    env_file: .env

networks:
  exchange_nw:
    driver: bridge

volumes:
  timescale-data:
