services:
  client:
    build:
      context: client
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app/
      - /app/node_modules
    networks:
      - exchange_nw

  api:
    build:
      context: api
      target: dev
    ports:
      - 4000:4000
    volumes:
      - ./api/:/app/
      - /app/node_modules
    depends_on:
      - order_queue
    networks:
      - exchange_nw
    environment:
      - REDIS_URL=redis://order_queue:6379

  matching-engine:
    build:
      context: matching-engine
      target: dev
    volumes:
      - ./matching-engine/:/app/
      - /app/node_modules
    depends_on:
      - order_queue
    networks:
      - exchange_nw
    environment:
      - REDIS_URL=redis://order_queue:6379

  order_queue:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - exchange_nw

networks:
  exchange_nw:
    driver: bridge
