version: '3.8'

services:
  mq:
    image: redis
    container_name: mq

  db:
    image: timescale/timescaledb-ha:pg16
    container_name: db
    env_file: .env-prod
    volumes:
      - timescale-data-prod:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      target: prod
    container_name: client
    env_file: .env-prod
    ports:
      - 3000:3000

  server:
    build:
      context: ./server
      target: prod
    container_name: server
    restart: always
    ports:
      - 4000:4000
    env_file: .env-prod
    depends_on:
      - mq
      - engine
      - db

  engine:
    build:
      context: ./engine
      target: prod
    container_name: engine
    env_file: .env-prod
    depends_on:
      - mq
      - db-processor

  db-processor:
    build:
      context: ./db-processor
      target: prod
    container_name: db-processor
    env_file: .env-prod
    depends_on:
      - mq
      - db

  web-sockets:
    build:
      context: ./web-sockets
      target: prod
    container_name: ws
    ports:
      - 5000:5000
    env_file: .env-prod
    depends_on:
      - mq

volumes:
  timescale-data-prod:
