import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import SessionWrapper from "./SessionWrapper";
import { Theme } from "@radix-ui/themes";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Radiation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} lg:container mx-auto min-h-screen max-w-screen`}
      >
        <SessionWrapper>
          <Theme appearance="dark">{children}</Theme>
        </SessionWrapper>
      </body>
    </html>
  );
}
